# Generated by Django 5.2.6 on 2025-10-20 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nacho2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mail', models.CharField(max_length=100)),
                ('propic', models.ImageField(blank=True, default='images/imagen6.jpg', upload_to='')),
            ],
        ),
    ]
