# Generated by Django 5.2.6 on 2025-10-22 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nacho2', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='person',
            name='propic',
            field=models.ImageField(default='images/imagen6.png', upload_to='profile'),
        ),
    ]
